name: MineSuiteEconomy
version: ${project.version}
description: EconomyPlugin
authors: [Kekshaus]
main: de.linzn.mineSuite.economy.EconomyPlugin
load: POSTWORLD
depend: [Vault]
softdepend: [MineSuiteCore]
api-version: 1.13
commands:
  money:
    description: Money command

permissions:
    mineSuite.economy.team:
        description: Alle Team Permissions
        children:
            mineSuite.economy.user: true
            mineSuite.economy.set: true
    mineSuite.economy.user:
        description: Alle User Permissions
        children:
            mineSuite.economy.help: true
            mineSuite.economy.balance: true
            mineSuite.economy.pay: true
            mineSuite.economy.top: true
    mineSuite.economy.help:
        description: Permissions
    mineSuite.economy.balance:
        description: Permissions
    mineSuite.economy.pay:
        description: Permissions
    mineSuite.economy.top:
        description: Permissions
    mineSuite.economy.set:
        description: Permissions