name: MineSuiteEconomy
version: ${project.version}
description: EconomyPlugin
authors: [Kekshaus]
main: de.linzn.mineSuite.economy.EconomyPlugin
load: POSTWORLD
depend: [Vault]
softdepend: [MineSuiteCore]
api-version: 1.13
commands:
  money:
    description: Money command

permissions:
    mineSuite.economy.team:
        description: Alle User Permissions
        children:
            mineSuite.economy.user: true